# Generated by Django 2.1.4 on 2019-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=64)),
                ('dimploma', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('experience', models.IntegerField()),
                ('skills', models.CharField(max_length=64)),
            ],
        ),
    ]
