# Generated by Django 2.1.4 on 2019-04-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dimploma',
            new_name='diploma',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='profile',
            new_name='profil',
        ),
    ]
